### ISSUE TITLE
Cannot run on terraform entreprise

### ISSUE THREAD

**Issue by Esya** [claranet/terraform-aws-lambda#24]
Just leaving this out there - This module cannot run on terraform entreprise because the `zip` command is not present. Not sure if there is a workaround for this..

```
* module.taskPlanner_cron.module.lambda.data.external.built: data.external.built: failed to execute "/terraform/scheduling-service/.terraform/modules/c205777ab1dadf9cdd9611349aa2639d/built.py": Traceback (most recent call last):
  File "/terraform/scheduling-service/.terraform/modules/c205777ab1dadf9cdd9611349aa2639d/build.py", line 146, in <module>
    create_zip_file(temp_dir, absolute_filename)
  File "/terraform/scheduling-service/.terraform/modules/c205777ab1dadf9cdd9611349aa2639d/build.py", line 100, in create_zip_file
    run('zip', '-r', target_file, '.')
  File "/terraform/scheduling-service/.terraform/modules/c205777ab1dadf9cdd9611349aa2639d/build.py", line 70, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'zip'
Traceback (most recent call last):
  File "/terraform/scheduling-service/.terraform/modules/c205777ab1dadf9cdd9611349aa2639d/built.py", line 31, in <module>
    subprocess.check_output(build_command, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/terraform/scheduling-service/.terraform/modules/c205777ab1dadf9cdd9611349aa2639d/build.py=[redacted]' returned non-zero exit status 1
```

**Comment by lorengordon** [comment]
The patch I submitted to add support for Windows, https://github.com/claranet/terraform-aws-lambda/pull/20, removes the dependency on `zip` being installed... 😁

**Comment by Esya** [comment]
@lorengordon Oh, that's great! I'll probably fork it then. I think it'd be even better to use [the built-in archive_file data source](https://www.terraform.io/docs/providers/archive/d/archive_file.html) to do this.

**Comment by lorengordon** [comment]
@Esya Definitely, here's my branch, https://github.com/lorengordon/terraform-aws-lambda/tree/windows-support. Hopefully that works for you!
